mindmap
    root((Quantum Computing))
        Analog QC
            Superconductors
                D-Wave
                    Dimod/D-Wave system
                    Part of quantum alliance
            Neutral Atoms
                Pasqal
                    Qiskit compatible
                QuEra
                    Premium access - via Centro Nazionale
        Digital QC
            Superconductors
                IBM
                    Qiskit
                    Limited free access - 10 min/month
                IQM
                    Qiskit-compatible
                    Limited free access - 30 credits/month
                    Premium access - via Cosma Belli
                Google
                    Circ
            Trapped Ions
                Quantinuum
                    Guppy
                IonQ
                    Part of quantum alliance
                    Headquarter in Rome
            Photons
                Quandela
                Xanadu
        Quantum inspired
            Fujitsu
                Digital annealer
                Free access via API
        Simulation
            NVIDIA
                CUDA-Q
            D-Wave
                QBsolv - hybrid solver
                Simulated annealing
